src/gama/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

import debug_toolbar
from cms import views
from cms.sitemaps import CatalogSitemap

from .sitemaps import StaticViewSitemap

sitemaps = {"static": StaticViewSitemap, "catalogo": CatalogSitemap}

admin.site.site_header = "Gama Estudio"
admin.site.site_title = "Gama Estudio"
admin.site.index_title = "Admin"


urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("", views.home, name="home"),
    path("catalogo/", views.CategoryList.as_view(), name="piece-category-list"),
    path("catalogo/<slug:category_slug>/", views.PieceList.as_view(), name="catalog"),
    path(
        "catalogo/<slug:category_slug>/<slug:slug>/",
        views.PieceDetails.as_view(),
        name="catalog_detail",
    ),
    path("talleres/", views.workshops, name="workshops"),
    path(
        "talleres/<slug:slug>", views.WorkshopDetail.as_view(), name="workshop_detail"
    ),
    path("nosotras/", views.us, name="us"),
    path("proyectos/", views.projects, name="projects"),
    path("contacto/", views.Contact.as_view(), name="contact"),
    path("faq/", views.FrequentQuestionList.as_view(), name="faq"),
    path("tienda/", include("shop.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("carrito", views.Cart.as_view(), name="cart"),
    path("carrito/<int:item_id>", views.CartItem.as_view(), name="cart_item"),
    path("carrito/detalles", views.cart_details, name="cart_details"),
    path("carrito/widget", views.cart_widget, name="cart_widget"),
    path("checkout", views.Checkout.as_view(), name="checkout"),
    path("pago", views.process_payment, name="process_payment"),
    path(
        "pago/order-details",
        views.checkout_order_details,
        name="checkout_order_details",
    ),
    path("pago/hecho", views.payment_done, name="payment_done"),
    path("pago/cancelado", views.payment_canceled, name="payment_cancelled"),
    path("pay-pal/create-order", views.paypal_create_order, name="paypal_create_order"),
    path("pay-pal/verify-order", views.paypal_verify_order, name="paypal_verify_order"),
    path(
        "pay-pal/capture-order", views.paypal_capture_order, name="paypal_capture_order"
    ),
    path(
        "orden/<int:pk>",
        views.OrderDetails.as_view(),
        name="order_details",
    ),
    path(
        "orden/<int:pk>/update-shipping-cost",
        views.update_order_shipping_cost,
        name="update-order-shipping-cost",
    ),
]

src/shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from solo.models import SingletonModel

from cms.models import Piece

from .constants import (
    MEXICO_STATES_OPTIONS,
    OrderStatus,
    PaymentStatus,
)
from .shipping import calculate_order_weight


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    session_id = models.CharField(max_length=240, null=True)
    name = models.CharField(default="", max_length=240, null=True, blank=True)
    email = models.EmailField(default="", null=True, blank=True)
    phone_number = PhoneNumberField(
        "número de teléfono",
        blank=True,
        default="",
    )
    rfc = models.CharField("RFC", default="", max_length=240, null=True, blank=True)

    def __str__(self):
        if self.name:
            return self.name

        return f"Anonymous: {self.session_id}"


class ShippingCostInfo(SingletonModel):
    shipping_cost_extra = models.DecimalField(
        "Precio por kg extra (MXN)", default=450, max_digits=7, decimal_places=2
    )

    @classmethod
    def get_cost_by_weight(cls, weight):
        max_cost = ShippingCost.get_closest_weight(weight)
        if max_cost:
            remain = max(weight - max_cost.weight, 0)
            extra = cls.get_solo().shipping_cost_extra
            return max_cost.price + (extra * remain)
        else:
            return 0


class ShippingCost(models.Model):
    info = models.ForeignKey(ShippingCostInfo, on_delete=models.CASCADE)
    weight = models.PositiveIntegerField("Peso (kg)", unique=True)
    price = models.DecimalField(
        "Precio (MXN)", default=0, max_digits=7, decimal_places=2
    )

    class Meta:
        ordering = ["weight"]

    def __str__(self):
        return f"{self.weight}kg= ${self.price}MXN"

    @classmethod
    def get_closest_weight(cls, target_weight):
        closest_shipping = (
            cls.objects.filter(weight__gte=target_weight).order_by("weight").first()
        )

        if (
            not closest_shipping
        ):  # If no weight >= target_weight, get the max weight available
            closest_shipping = cls.objects.order_by("-weight").first()

        return closest_shipping


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    postal_code = models.CharField(
        "código postal", max_length=240, blank=True, default=""
    )
    address_01 = models.CharField("dirección", max_length=240, blank=True, default="")
    address_02 = models.CharField(
        "casa, apartamento, etc", max_length=240, blank=True, default=""
    )
    state = models.CharField(
        "estado",
        max_length=20,
        blank="True",
        default="",
        choices=MEXICO_STATES_OPTIONS,
    )
    city = models.CharField("ciudad", max_length=240, blank=True, default="")
    references = models.TextField("referecias", blank=True, default="")

    def __str__(self):
        return f"{self.address_01} {self.state} {self.city}"


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_created = models.DateTimeField(auto_now_add=True)
    payment_status = models.CharField(
        choices=PaymentStatus.choices, max_length=50, default=PaymentStatus.UNPAID
    )
    order_status = models.CharField(
        choices=OrderStatus.choices, max_length=50, default=OrderStatus.OPEN
    )
    shipping_address = models.ForeignKey(
        ShippingAddress, on_delete=models.SET_NULL, blank=True, null=True
    )
    transaction_id = models.CharField(max_length=200, null=True)
    subtotal_cost = models.DecimalField(
        default=None,
        max_digits=7,
        decimal_places=2,
        editable=False,
        null=True,
    )
    shipping_cost = models.DecimalField(
        default=None,
        max_digits=7,
        decimal_places=2,
        editable=False,
        null=True,
    )

    def __str__(self):
        return f"Order {self.id}"

    def get_absolute_url(self):
        return reverse("order_details", kwargs={"pk": self.pk})

    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super().from_db(db, field_names, values)

        # save original values, when model is loaded from database,
        # in a separate attribute on the model
        instance._loaded_values = dict(zip(field_names, values, strict=False))

        return instance

    def save(self, *args, **kwargs):
        if (
            not self._state.adding
            and (self.payment_status != self._loaded_values["payment_status"])
            and self.payment_status == PaymentStatus.PAID
        ):
            self.subtotal_cost = self.get_subtotal_cost_by_stock
            self.shipping_cost = self.get_shipping_cost_by_stock
        super().save(*args, **kwargs)

    @property
    def get_weight(self):
        items = self.orderitem_set.filter(product__status="stck")
        return calculate_order_weight(items)

    @property
    def get_subtotal_cost_by_stock(self):
        items = self.orderitem_set.filter(product__status="stck")
        return sum([item.get_total_cost for item in items])

    @property
    def get_shipping_cost_by_stock(self):
        items = self.orderitem_set.filter(product__status="stck")
        weight = calculate_order_weight(items)
        price = ShippingCostInfo.get_cost_by_weight(weight)
        return price

    @property
    def get_total_cost_by_stock(self):
        subtotal = self.get_subtotal_cost_by_stock
        shipping = self.get_shipping_cost_by_stock
        return subtotal + shipping

    @property
    def get_subtotal_cost(self):
        if self.payment_status == PaymentStatus.PAID:
            return self.subtotal_cost

        return self.get_subtotal_cost_by_stock

    get_subtotal_cost.fget.short_description = "Subtotal"

    @property
    def get_shipping_cost(self):
        if self.payment_status == PaymentStatus.PAID:
            return self.shipping_cost

        return self.get_shipping_cost_by_stock

    get_shipping_cost.fget.short_description = "Shipping"

    @property
    def get_total_cost(self):
        if self.payment_status == PaymentStatus.PAID:
            return self.subtotal_cost + self.shipping_cost

        return self.get_total_cost_by_stock

    get_total_cost.fget.short_description = "Total"

    @property
    def get_cart_items_count(self):
        items = self.orderitem_set.all()
        return len(items)


class OrderItem(models.Model):
    product = models.ForeignKey(Piece, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.product:
            return f"Order Item for {self.product.name}"
        return "Order Item --"

    @property
    def get_total_cost(self):
        return self.product.price_discounted * self.quantity

src/shop/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import RegionalPhoneNumberWidget

from .constants import MEXICO_STATES_OPTIONS


class UpdateOrderShippingCostForm(forms.Form):
    order_id = forms.IntegerField()


class ProductActionForm(forms.Form):
    product_id = forms.IntegerField(label="Product Id")


class CheckoutForm(forms.Form):
    name = forms.CharField(max_length=240)
    email = forms.EmailField()
    rfc = forms.CharField(label="RFC", max_length=15)
    phone_number = PhoneNumberField(
        region="MX",
        widget=RegionalPhoneNumberWidget(
            attrs={"placeholder": "## #### ####"},
        ),
    )
    shipping_address_id = forms.IntegerField()
    postal_code = forms.IntegerField(label="código postal")
    address_01 = forms.CharField(label="dirección", max_length=240)
    address_02 = forms.CharField(
        label="casa, apartamento, etc", max_length=240, required=False
    )
    state = forms.ChoiceField(label="estado", choices=MEXICO_STATES_OPTIONS)
    city = forms.CharField(label="ciudad", max_length=240)
    references = forms.CharField(
        label="referencias", widget=forms.Textarea, required=False
    )

src/shop/templates/shop/partials/cart-add-button.html
{% if object.status == 'stck' %}
<form class="add-to-cart-form" hx-post="{% url 'cart' %}" hx-swap="outerHTML">
  {% csrf_token %}
  <input type="text" name="product_id" value="{{object.id}}" hidden />

  <button type="submit" class="button-buy-pice button-icon">
    <span>agregar al carrito</span>
  </button>
</form>
{% endif %}

src/shop/templates/shop/partials/cart-add-success.html
<div class="cart-add-success">
  <span class="message success">pieza agregada a tu carrito</span>
  <a href="{% url 'cart' %} " class="button">ir al carrito</a>
</div>

src/shop/templates/shop/partials/cart-details.html
{% load humanize %}
{% with order_items=cart_order.orderitem_set.all %}
<div
  id="cart-details"
  class="wrapper"
  hx-get="{% url 'cart_details' %}"
  hx-trigger="every 10s"
  hx-swap="outerHTML"
>
  <h1>mi carrito</h1>

  {% if order_items|length %}
  <section class="cart-product-list">
    {% for item in order_items %}
    {% include 'shop/partials/cart-row.html' %} 
    {% endfor %}
  </section>

  <section class="cart-product-sub-total">
    <h2>sub total</h2>
    <span class="cart-total-price price"
      >MXN ${{ cart_order.get_subtotal_cost|intcomma }}</span
    >
  </section>

  <section class="cart-product-shipping">
    <h2>envío</h2>
    <span class="cart-shipping-price price"
      >MXN ${{ cart_order.get_shipping_cost|intcomma }}</span
    >
  </section>

  <section class="cart-product-total">
    <h2>total</h2>
    <span class="cart-total-price price">MXN ${{ cart_order.get_total_cost|intcomma }}</span>
  </section>

  <section class="cart-navigation">
    <a class="button" href="{% url 'checkout' %}">continuar al pago</a>
  </section>
  {% else %}
  <h2>está vacío</h2>
  {% endif %}
</div>
{% endwith %}

src/shop/templates/shop/partials/cart-remove-button.html
<form
  class="cart-product-delete"
  hx-delete="{% url 'cart_item' item_id=item.id %}"
  hx-target="closest #cart-details"
  hx-swap="outerHTML"
>
  {% csrf_token %}
  <button class="-secondary" type="submit">remover</button>
</form>

src/shop/templates/shop/partials/cart-row.html
{% load humanize %}
<article
  class="cart-product-item"
  data-status="{{item.product.status}}"
>
<div class="cart-product-name-wrapper">
  <h2 class="cart-product-name">
    <a href={{item.product.get_absolute_url }}>{{ item.product.name }}</a>{% if item.product.status == "sold" %} (agotado){% endif %}
  </h2>
  <div class="hide-desktop">
    {% include 'shop/partials/cart-remove-button.html' with object=item %}
  </div>
</div>
  <div class="cart-product-info">
    <span class="cart-product-price price">MXN ${{ item.get_total_cost|intcomma|floatformat:2}}</span>
    <div class="hide-mobile">
      {% include 'shop/partials/cart-remove-button.html' with object=item %}
    </div>
  </div>
</article>

src/shop/templates/shop/partials/cart-widget.html
<li class="cart-indicator" data-items-count="{{cart_items_count}}" hx-get="{% url 'cart_widget' %}"
  hx-trigger="cart-updated from:body" hx-swap="outerHTML">
  <a href="{% url 'cart' %}">
    {% if cart_order.get_cart_items_count > 0 %}
    <span class="cart-indicator-count">{{ cart_order.get_cart_items_count }}</span>
    {% endif %}
    <span>carrito</span>
  </a>
</li>

src/shop/templates/shop/partials/checkout-order-details.html
{% load humanize %}
{% with shipping_address=cart_order.shipping_address %}
<div class="order-details"
  id="checkout-order-details"
  hx-get="{% url 'checkout_order_details' %}"
  hx-trigger="every 10s"
  hx-swap="outerHTML"
>
  <section class="order-product-list">
    {% for item in cart_order.orderitem_set.all %}
    <article class="order-product-item" data-status="{{item.product.status}}">
      <h2 class="order-product-name">{{ item.product.name }}{% if item.product.status == "sold" %} (agotado){% endif %}
      </h2>
      <span class="order-product-price price">MXN ${{ item.product.price_discounted|floatformat:2|intcomma }}</span>
    </article>
    {% endfor %}
  </section>

  <section class="order-product-sub-total">
    <h2>sub total</h2>
    <span class="cart-total-price price">MXN ${{ cart_order.get_subtotal_cost|floatformat:2|intcomma }}</span>
  </section>

  <section class="order-info">
    <h2>info</h2>
    <div class="rich-text">
      <p>
      {{ cart_order.customer.name }}<br>
      {{ cart_order.customer.rfc }}<br>
      {{ cart_order.customer.phone_number}}<br>
      {{ cart_order.customer.email }}
      </p>

      <p>
      <span>{{ shipping_address.address_01 }} </span><br/>
      {% if shipping_address.address_02 %}<span>{{ shipping_address.address_02 }}</span><br/>{% endif %}
      <span>{{ shipping_address.get_state_display }}</span><br>
      <span>{{ shipping_address.city }}, </span>
      <span>{{ shipping_address.postal_code }}</span>
      </p>
    </div>
  </section>


  <section class="order-product-shipping">
    <h2>envio</h2>
    <span class="cart-shipping-price price">MXN ${{cart_order.get_shipping_cost|floatformat:2|intcomma }}</span>
  </section>

  <section class="order-product-total">
    <h2>total</h2>
    <span class="cart-total-price price">MXN ${{ cart_order.get_total_cost|floatformat:2|intcomma }}</span>
  </section>
</div>
{% endwith %}

src/shop/templates/shop/partials/checkout-order-shipping-cost-error.html
{% load humanize %}

<section class="order-product-shipping">
  <h2>envio</h2>
  <span class="cart-shipping-price price">ERROR</span>
</section>

src/shop/templates/shop/partials/checkout-order-shipping-cost.html
{% load humanize %}

<section class="order-product-shipping">
  <h2>envio</h2>
  <span class="cart-shipping-price price">MXN ${{shipping_cost|intcomma}}</span>
</section>